//===- FlirOps.td - Entry point for Flir python bindings -*- tablegen -*-===//
//
// This file is the entry point for generating Python op bindings for the Flir
// dialect. It includes the main dialect op definitions.
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_FLIR_OPS
#define PYTHON_BINDINGS_FLIR_OPS

include "flir/FlirOps.td"

#endif // PYTHON_BINDINGS_FLIR_OPS
