//===- RocirOps.td - Entry point for Rocir python bindings -*- tablegen -*-===//
//
// This file is the entry point for generating Python op bindings for the Rocir
// dialect. It includes the main dialect op definitions.
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_ROCIR_OPS
#define PYTHON_BINDINGS_ROCIR_OPS

include "rocir/RocirOps.td"

#endif // PYTHON_BINDINGS_ROCIR_OPS
